fixtures:
  repositories:
     stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
     archive: "git://github.com/puppet-community/puppet-archive.git"
     docker: "git://github.com/garethr/garethr-docker.git"
     wget: "git://github.com/maestrodev/puppet-wget.git"
     apt: https://github.com/puppetlabs/puppetlabs-apt.git
  symlinks:
    grafana: "#{source_dir}"
