fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    docker: "https://github.com/garethr/garethr-docker.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core.git
